# Generated by Django 4.1.1 on 2022-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Имя валюты')),
                ('price', models.FloatField(verbose_name='Курс валюты')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo1', models.FileField(upload_to='logo/')),
                ('logo2', models.FileField(upload_to='logo/')),
                ('logo3', models.FileField(upload_to='logo/')),
                ('logo4', models.FileField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название сайта')),
                ('wallet', models.CharField(max_length=100, verbose_name='Кашёлёк')),
                ('logo_site', models.ImageField(upload_to='logo/')),
                ('decription', models.TextField()),
                ('cript_1', models.CharField(max_length=50, verbose_name='обьём1')),
                ('cript_2', models.CharField(max_length=50, verbose_name='обьём2')),
                ('cript_3', models.CharField(max_length=50, verbose_name='обьём3')),
                ('rez_1', models.CharField(max_length=50, verbose_name='резерв1')),
                ('rez_2', models.CharField(max_length=50, verbose_name='резерв2')),
                ('rez_3', models.CharField(max_length=50, verbose_name='резерв3')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Statics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Статика')),
                ('text', models.CharField(max_length=50, verbose_name='Текст статистики')),
                ('img', models.ImageField(upload_to='stat/')),
            ],
        ),
    ]
